#!/bin/bash
# 需预先安装 sshpass 服务，在明确不能配置免密的情况下，可使用这样的读密码文件，远程执行命令的方式
# 如果允许配置免密，当然是用Ansible，后续会更新Ansible的yaml文件
# 选择怎么读secret有很多方式，for循环接收起止位置这种方式方便从任意位置开始，比如遇到意外情况中断可以从中断处开始，也可以对单个机器进行操作

USER=$1                #用户   root/···
USER_SECRET=$2         #密码文件
IP_NET=$3              #网络段 如192.168.1

echo "please input min ip numbers:"
read -p "" ip_min                      #ip最后一位
echo "please input max ip numbers:"
read -p "" ip_max                      #ip最后一位

for ((i=${ip_min}; i<=${ip_max}; i++))   #读取到最后一行
do
  #确定ip所在行
  location=`cat ${USER_SECRET} |grep -n ${IP_NET}.${i} |awk -F ":" '{print $1}'`
  #确定ip的密码，密码要在第二列，这个$2不是指位置上的第二列，而是有参数的第二列，空格会被忽略掉
  ip_secret=`cat ${USER_SECRET} |awk NR==${location}'{print $2}'`
  #   -o StrictHostKeyChecking=no  忽略校验， ConnectTimeout=10  10s超时限制， <<eof  远程要执行的命令  eof
  sshpass -p ${ip_secret} ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${USER}@${IP_NET}.${i} <<EOF


EOF
done

